### ISSUE TITLE
make a test

### ISSUE THREAD

**Issue by t-jindai** [kashiro/fly-sass#3]

**Comment by ghost** [comment]
No time? :smile: 

Please [see here](https://github.com/bucaran/fly-babel/tree/master/test). 

> BTW would love if you could add me as a collaborator!

**Comment by t-jindai** [comment]
@bucaran 

I have added test and update tag to `v0.2.0` from `v0.1.3`.
Then I could not `npm publish`...

Do you have any idea about it ?  :sweat:  :bow: 

```
─$ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/tomoyuki/.nodebrew/node/v0.12.7/bin/node" "/Users/tomoyuki/.nodebrew/current/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 0.2.0." : fly-sass
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tomoyuki/workspace/fly-sass/npm-debug.log
```

npm-debug.log

``````
0 info it worked if it ends with ok
1 verbose cli [ '/Users/tomoyuki/.nodebrew/node/v0.12.7/bin/node',
1 verbose cli   '/Users/tomoyuki/.nodebrew/current/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/tomoyuki/workspace/fly-sass',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/tomoyuki/.npm/fly-sass/0.2.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/tomoyuki/.npm/fly-sass/0.2.0/package.tgz',
9 verbose tar pack   '/Users/tomoyuki/workspace/fly-sass' ]
10 verbose tarball /Users/tomoyuki/.npm/fly-sass/0.2.0/package.tgz
11 verbose folder /Users/tomoyuki/workspace/fly-sass
12 info prepublish fly-sass@0.2.0
13 verbose addLocalTarball adding from inside cache /Users/tomoyuki/.npm/fly-sass/0.2.0/package.tgz
14 silly cache afterAdd fly-sass@0.2.0
15 verbose afterAdd /Users/tomoyuki/.npm/fly-sass/0.2.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/tomoyuki/.npm/fly-sass/0.2.0/package/package.json written
17 silly publish { name: 'fly-sass',
17 silly publish   version: '0.2.0',
17 silly publish   description: 'node sass plugin for Fly',
17 silly publish   license: 'MIT',
17 silly publish   homepage: 'https://github.com/kashiro/fly-sass',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/kashiro/fly-sass.git' },
17 silly publish   bugs: { url: 'https://github.com/kashiro/fly-sass/issues' },
17 silly publish   contributors: 'https://github.com/kashiro/fly-sass/graphs/contributors',
17 silly publish   main: 'index.js',
17 silly publish   scripts: { test: 'fly && node test/test.js' },
17 silly publish   keywords: [ 'fly', 'node-sass' ],
17 silly publish   author:
17 silly publish    { name: 'Tomoyuki Kashiro',
17 silly publish      email: 'ksrtmyk@gmail.com',
17 silly publish      url: 'http://kashiro.github.com' },
17 silly publish   dependencies: { 'node-sass': '^3.2.0', 'object-assign': '^3.0.0' },
17 silly publish   devDependencies: { fly: '^0.7.1', 'fly-sass': './' },
17 silly publish   engines: { iojs: '>= 1.0.0', node: '>= 0.11.0' },
17 silly publish   readme: '<div align="center">\n  <a href="http://github.com/flyjs/fly">\n    <img width=200px  src="https://cloud.githubusercontent.com/assets/8317250/8733685/0be81080-2c40-11e5-98d2-c634f076ccd7.png">\n  </a>\n</div>\n\n> [node-sass](https://github.com/sass/node-sass) plugin for _[Fly][fly]_.\n\n[![][fly-badge]][fly]\n[![npm package][npm-ver-link]][releases]\n[![][dl-badge]][npm-pkg-link]\n[![][travis-badge]][travis-link]\n[![][mit-badge]][mit]\n\n## Usage\n> Check out the [documentation](https://github.com/sass/node-sass) to see the available options.\n\n### Install\n\n```a\nnpm install -D fly-sass\n```\n\n### Example\n\nCheck [Flyfile.js](https://github.com/kashiro/fly-sass/blob/master/Flyfile.js) and [test](https://github.com/kashiro/fly-sass/blob/master/test) directory :)\n\n```js\nexport default function* () {\n  yield this.clear("test/style.css")\n  yield this\n    .source("test/src/style.scss")\n    .sass({\n      outputStyle: "compressed",\n      includePaths: ["test/src/imports"],\n      sourceMap: true\n    })\n    .target("test")\n}\n```\n\n# License\n\n[MIT][mit] © [Tomoyuki Kashiro][author] et [al][contributors]\n\n\n[mit]:          http://opensource.org/licenses/MIT\n[author]:       http://tomoyukikashiro.me\n[contributors]: https://github.com/kashiro/fly-sass/graphs/contributors\n[releases]:     https://github.com/kashiro/fly-sass/releases\n[fly]:          https://www.github.com/flyjs/fly\n[fly-badge]:    https://img.shields.io/badge/fly-JS-05B3E1.svg?style=flat-square\n[mit-badge]:    https://img.shields.io/badge/license-MIT-444444.svg?style=flat-square\n[npm-pkg-link]: https://www.npmjs.org/package/fly-sass\n[npm-ver-link]: https://img.shields.io/npm/v/fly-sass.svg?style=flat-square\n[dl-badge]:     http://img.shields.io/npm/dm/fly-sass.svg?style=flat-square\n[travis-link]:  https://travis-ci.org/kashiro/fly-sass\n[travis-badge]: http://img.shields.io/travis/kashiro/fly-sass.svg?style=flat-square\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'aed86183f8281c6f23246b13d55de0278a510b9b',
17 silly publish   _id: 'fly-sass@0.2.0',
17 silly publish   _shasum: 'c3cc281fda379dbae0f367cfd3579ff85c6ec2d8',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name fly-sass
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/fly-sass
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/tomoyuki/.npm/fly-sass/0.2.0/package.tgz
25 verbose request uri https://registry.npmjs.org/fly-sass
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 14:51:00
28 verbose request using bearer token for auth
29 verbose request id f4008f0d2b2a8cc0
30 http request PUT https://registry.npmjs.org/fly-sass
31 http 403 https://registry.npmjs.org/fly-sass
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=60',
32 verbose headers   'content-length': '95',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Sun, 23 Aug 2015 05:51:01 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-nrt6132-NRT',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1440309060.399034,VS0,VE1521' }
33 verbose request invalidating /Users/tomoyuki/.npm/registry.npmjs.org/fly-sass on PUT
34 error publish Failed PUT 403
35 verbose stack Error: "You cannot publish over the previously published version 0.2.0." : fly-sass
35 verbose stack     at CachingRegistryClient.<anonymous> (/Users/tomoyuki/.nodebrew/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
35 verbose stack     at Request._callback (/Users/tomoyuki/.nodebrew/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
35 verbose stack     at Request.self.callback (/Users/tomoyuki/.nodebrew/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:354:22)
35 verbose stack     at Request.emit (events.js:110:17)
35 verbose stack     at Request.<anonymous> (/Users/tomoyuki/.nodebrew/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1207:14)
35 verbose stack     at Request.emit (events.js:129:20)
35 verbose stack     at IncomingMessage.<anonymous> (/Users/tomoyuki/.nodebrew/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1153:12)
35 verbose stack     at IncomingMessage.emit (events.js:129:20)
35 verbose stack     at _stream_readable.js:908:16
35 verbose stack     at process._tickCallback (node.js:355:11)
36 verbose statusCode 403
37 verbose pkgid fly-sass
38 verbose cwd /Users/tomoyuki/workspace/fly-sass
39 error Darwin 14.4.0
40 error argv "/Users/tomoyuki/.nodebrew/node/v0.12.7/bin/node" "/Users/tomoyuki/.nodebrew/current/bin/npm" "publish"
41 error node v0.12.7
42 error npm  v2.11.3
43 error code E403
44 error "You cannot publish over the previously published version 0.2.0." : fly-sass
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
``````

**Comment by ghost** [comment]
There was a version conflict. It seems that `0.2.0` was already published at some point?

Maybe you can bump the version to `0.2.1` and try again.

**Comment by t-jindai** [comment]
@bucaran 

Thank you for your response!
It was correct. :bow: 
I could update `v0.2.1` and have added test :+1: 

( I did not know when v0.2.0 was registerd .... :sweat_drops:  )

Thank you for your cooperation. !
